#!r6rs
;; Automatically generated by private/make-aliased-libraries.sps
(library (srfi s25)
  (export
    array
    array-end
    array-rank
    array-ref
    array-set!
    array-start
    array?
    make-array
    shape
    share-array)
  (import (srfi s25 multi-dimensional-arrays))
)
