#!r6rs
;; Automatically generated by private/make-aliased-libraries.sps
(library (srfi s37)
  (export
    args-fold
    option
    option-names
    option-optional-arg?
    option-processor
    option-required-arg?
    option?)
  (import (srfi s37 args-fold))
)
