#!r6rs
;; Automatically generated by private/make-aliased-libraries.sps
(library (srfi s38)
  (export
    read-with-shared-structure
    read/ss
    write-with-shared-structure
    write/ss)
  (import (srfi s38 with-shared-structure))
)
