#!r6rs
;; Automatically generated by private/make-aliased-libraries.sps
(library (srfi s78)
  (export
    check
    check-ec
    check-passed?
    check-report
    check-reset!
    check-set-mode!)
  (import (srfi s78 lightweight-testing))
)
