#!r6rs
;; Automatically generated by private/make-aliased-libraries.sps
(library (srfi s98)
  (export
    get-environment-variable
    get-environment-variables)
  (import (srfi s98 os-environment-variables))
)
